config/routes.rb
Rails.application.routes.draw do
  # resources :cat_tags
  resources :tags
  get 'reservations/:id/cat_review/new', to: 'cat_reviews#new', as: :new_cat_review
  resources :cat_reviews, only: [:show, :create]
  get 'reservations/:id/renter_review/new', to: 'renter_reviews#new', as: :new_renter_review
  resources :renter_reviews, only: [:show, :create]
  get '/', to: 'cats#homepage', as: :homepage 
  get '/cat_stats', to: 'cats#cat_stats', as: :cat_stats
  post 'cats/search', to: 'cats#search', as: :search
  resources :cats
  get 'cats/:id/reservation/new', to: 'reservations#new', as: :new_reservation
  resources :reservations
  get 'users/my_profile', to: 'users#myprofile', as: :my_profile
  resources :users
  resources :sessions, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/login', to: 'sessions#new', as: :login
  delete '/logout', to: 'sessions#destroy', as: :logout
end

app/models/user.rb
class User < ApplicationRecord
has_many :cats, foreign_key: 'owner_id'
has_many :owner_reservations, through: :cats, source: :reservations
has_many :reservations, foreign_key: 'renter_id'
has_many :rented_cats, through: :reservations, source: :cat

has_secure_password
validates :name, presence: true
validates :username, presence: true, uniqueness: true
validates :password, presence: true
validates :password, confirmation: {case_sensitive: true}
validates :password, length: {minimum: 5}

  def top_3_cats #top 3 highest rated cats. If no cats, returns nil
   cats.length > 0 ? cats.sort_by{|cat| cat.overall_rating}.reverse[0..2] : nil
  end


  def self_reviews_as_renter #Reviews of user as the renter
    reservations.map{|r| r.renter_review}.select{|r| r != nil}
  end

  def written_reviews
    (reservations.map{|r| r.cat_review} + owner_reservations.map{|r| r.renter_review}).select{|r| r != nil}
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized, only: [:edit, :destroy]
  before_action :already_signed_in?, only: :new
  
    def new
      @user = User.new
    end

    def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to my_profile_path
      else
        flash[:errors] = @user.errors.full_messages
        redirect_to new_user_path
      end
    end

    def myprofile
      @user = User.find_by(id: session[:user_id])
      @cats = @user.cats
      @reservations = @user.reservations
      @reviews_of_me = @user.self_reviews_as_renter
    end

    def show
      @user = User.find_by(id: params[:id])
      @cats = @user.cats
    end


    private

    def user_params
      params.require(:user).permit(:name, :username, :password, :password_confirmation)
    end

    def layout
      session[:user_id] ? "application" : "account_menu"
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user do |f|  %>
<p><%= f.label :username %></p>
<p><%= f.text_field :username %></p>
<br>
<p><%= f.label :password %></p>
<p><%= f.password_field :password %></p>
<br>
<p><%= f.label :password_confirmation, "Confirm Password"%></p>
<p><%= f.password_field :password_confirmation%></p>
<br>
<p><%= f.label :name, "Display Name" %></p>
<p><%= f.text_field :name %></p>
<br>
<div style="text-align:center;">
<br>
<%= f.submit "Submit" %>
</div>
<% end %>

app/views/users/myprofile.html.erb
 
<div class='profile'>
<h1 style='border:solid; padding:50px;'>My Profile</h1>
<div class="button">
<%= button_to "Add a New Cat", new_cat_path, method: :get %>
</div>
<br><br>
<h2 style="float:left;"><u>My Cats</u></h2>
<br><br>
<%# <div class="form"> %>
<% if @cats.length > 0  %>
<%@cats.each do |cat|%>
<div class='cat'>
  <%= render partial: "layouts/cat_display", locals: {cat: cat} %>
    <br><br>
    <div style="text-align: left; margin-left: 50px;">
    <h3>Reservations</h3>
    <h4>
    <% if cat.reservations.length > 0 %>
      <% cat.reservations.each do |reservation|%>
    
      <%= link_to "#{reservation.date.to_s(:custom_datetime)}", reservation %>

        <% end %></h4></div>
      <% else %>
    <p>None</p>
    <% end %>
    <br><br>
  <% end %></div>
<% else %>
<p>None</p>
<% end %>

<br><br>

<h2><u>My Reservations</u></h2>
<% if @reservations.length > 0 %>
    <% @reservations.each do |reservation| %>
      <%= link_to "#{reservation.date.to_s(:custom_datetime)} #{reservation.cat.name}", reservation %>
      <br>
    <% end  %>
<% else %>
  <p>None</p>
<% end %>

<br><br>

<h2><u>Reviews of Me</u></h2>
<% if @reviews_of_me && !@reviews_of_me.empty? %>
<%@reviews_of_me.each do |review|%>
     <%= link_to review.reservation.cat.owner.name, review.reservation.cat.owner %>
    <p><%=("⭐️" * review.rating)+("☆" * (5 - review.rating))%><%= review.rating.to_f %>/5</p>
    <p>"<%= review.review %>"</p>
  <%end%>
<% else %>
  <p>None</p>
<% end %>
</div>

</div>

app/views/users/new.html.erb
<% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <div class='error'><%=error%></div>
        <% end %>
    <% end %>
 
<div class='form'>
<h1>Create An Account</h1>
<br><br>
<%= render 'form' %>
<br><br>
Already have an account? Click <a href='/login'>Sign In</a>
</div>
</div>

app/views/users/show.html.erb
 

<h1><%=@user.name%></h1>
<br><br>
<h2><%=@user.name%>'s Cats</h2>
<% if @cats.length > 0 %>
  <%@cats.each do |cat|%>
    <%= render partial: "layouts/cat_display", locals: {cat: cat} %>
    <br><br>
    <% end %>
<%else %>
  <p>None</p>
  <% end %>
  </div>