config/routes.rb
Rails.application.routes.draw do
  # resources :cat_tags
  resources :tags
  get 'reservations/:id/cat_review/new', to: 'cat_reviews#new', as: :new_cat_review
  resources :cat_reviews, only: [:show, :create]
  get 'reservations/:id/renter_review/new', to: 'renter_reviews#new', as: :new_renter_review
  resources :renter_reviews, only: [:show, :create]
  get '/', to: 'cats#homepage', as: :homepage 
  get '/cat_stats', to: 'cats#cat_stats', as: :cat_stats
  post 'cats/search', to: 'cats#search', as: :search
  resources :cats
  get 'cats/:id/reservation/new', to: 'reservations#new', as: :new_reservation
  resources :reservations
  get 'users/my_profile', to: 'users#myprofile', as: :my_profile
  resources :users
  resources :sessions, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/login', to: 'sessions#new', as: :login
  delete '/logout', to: 'sessions#destroy', as: :logout
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :renter, class_name: 'User'
    belongs_to :cat
    has_one :cat_review
    has_one :renter_review
    validates :date, date: { after: Proc.new { Date.today } }
    validates :date, uniqueness: { scope: :cat_id, message: "is already reserved for that cat." }
    validates :date, presence: true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authorized
    before_action :find_reservation, only: [:show, :edit, :update, :destroy]


    def index
        @reservations = Reservation.all.sort_by{ |r| r.date}
    end

    def show
    end

    def new
        @reservation = Reservation.new
        @cat_id = params[:id]
        @cat = Cat.find_by(id: params[:id])
    end

    def create
        @reservation = Reservation.new(reservation_params)
        @reservation.renter_id = session[:user_id]
        if @reservation.save
            redirect_to @reservation
        else
            flash[:errors] = @reservation.errors.full_messages
            redirect_to new_reservation_path(params[:reservation][:cat_id])
        end
    end

    def edit
        if session[:user_id] == @reservation.renter_id
          render :edit
        else
          flash[:errors] = []
          redirect_to @reservation
        end
    end

    def update
        if @reservation.update(reservation_params)
            redirect_to @reservation
        else
            flash[:errors] = @reservation.errors.full_messages
            redirect_to edit_reservation_path(@reservation)
        end
    end

    def destroy
        @reservation.delete
        redirect_to my_profile_path
    end

    private
    def find_reservation
        @reservation = Reservation.find_by(id: params[:id])
    end

    def reservation_params
        params.require(:reservation).permit(:cat_id, :date)
    end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/edit.html.erb
 

<%= form_with model: @reservation do |f| %>
    <input type="hidden" name="cat_id" value=<%=@cat_id%>>
    <p><%= f.label :date %></p>
    <%= f.date_field :date %>
    <br><br>
    <%= f.submit %>
<% end %>
</div>

app/views/reservations/index.html.erb
<h1>Reservations</h1>

<ul>
<% @reservations.each do |reservation| %>
    <div class="catinfo"><li><%= link_to "#{reservation.date.to_s(:custom_datetime)} #{reservation.cat.name}", reservation %></li></div>
<% end  %>
</ul>
</div>

app/views/reservations/new.html.erb
 

<h1>Rent <%= @cat.name %></h1>
<div class="form">
<%= form_with model: @reservation do |f| %>
    <input type="hidden" name="reservation[cat_id]" value=<%=@cat_id%>>
    <p><%= f.label :date %></p>
    <%= f.date_field :date %>
    <br><br>
    <%= f.submit %>
<% end %>
</div>

app/views/reservations/show.html.erb
 

<h1><%= @reservation.date.to_s(:custom_datetime) %></h1><br>
<h2>Cat: <%= link_to @reservation.cat.name, @reservation.cat %></h2><br>

<% if session[:user_id] == @reservation.renter_id %>
<h2>Owner: <%= link_to @reservation.cat.owner.name, @reservation.cat.owner %></h2>
<div style="text-align:center;">
<%= button_to "Review this Cat", new_cat_review_path(params[:id]), method: :get %>
<%= button_to "Edit this Reservation", edit_reservation_path(@reservation), method: :get %>
<%= button_to "Cancel this Reservation", reservation_path(@reservation), method: :delete%>
</div>
<% end %>


<% if session[:user_id]  == @reservation.cat.owner_id %>
<h2>Renter: <%= link_to @reservation.renter.name, @reservation.renter %></h2>
<div style="text-align:center;">
<%= button_to "Review this Renter", new_renter_review_path(params[:id]), method: :get %>
<%= button_to "Cancel this Reservation", reservation_path(@reservation), method: :delete %>
</div>
<% end %>