config/routes.rb
Rails.application.routes.draw do
  # resources :cat_tags
  resources :tags
  get 'reservations/:id/cat_review/new', to: 'cat_reviews#new', as: :new_cat_review
  resources :cat_reviews, only: [:show, :create]
  get 'reservations/:id/renter_review/new', to: 'renter_reviews#new', as: :new_renter_review
  resources :renter_reviews, only: [:show, :create]
  get '/', to: 'cats#homepage', as: :homepage 
  get '/cat_stats', to: 'cats#cat_stats', as: :cat_stats
  post 'cats/search', to: 'cats#search', as: :search
  resources :cats
  get 'cats/:id/reservation/new', to: 'reservations#new', as: :new_reservation
  resources :reservations
  get 'users/my_profile', to: 'users#myprofile', as: :my_profile
  resources :users
  resources :sessions, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/login', to: 'sessions#new', as: :login
  delete '/logout', to: 'sessions#destroy', as: :logout
end

app/models/cat.rb
class Cat < ApplicationRecord
    belongs_to :owner, class_name: 'User'
    has_many :reservations, dependent: :destroy
    has_many :cat_tags, dependent: :destroy
    has_many :tags, through: :cat_tags
    has_one_attached :image


    validates :name, presence: true

    def tags_attributes=(tag_attributes)
        tag_attributes.values.each do |tag_attribute|
            if !tag_attribute[:name].blank?
                tag = Tag.find_or_create_by(tag_attribute)
                self.tags << tag
            end
        end
    end

    def self.search_by_attributes(params)
       self.select{|c| c.attributes.values.any?{|v| v.to_s.downcase.include?(params.downcase)}}
    end

    def self.search_by_owner(params)
        self.select{|c| c.owner.name.downcase.include?(params.downcase)}
    end

    def self.search_by_tags(params)
        @tags = Tag.select{|tag| tag.name.downcase.include?(params)}
        @cats = @tags.map do |tag|
            tag.cats
        end.flatten
    end

    def reviews #all reviews for cat. Returns hash w/ reviewer, review, rating
        self.reservations.map{|r| r.cat_review}.select{|c_r| c_r != nil}
    end

    def overall_rating #over-all rating as float. If no reviews, returns 0
        reviews.length > 0? (reviews.map{|r| r[:rating]}.sum.to_f / reviews.count).round(2) : 0
    end

    def self.featured #returns most popular cat by rating
        all.sort_by{|cat| cat.overall_rating}.last
    end

    def self.most_popular #returns 3 most popular by reservation count
    @cats = self.all.reject{|cat| cat == Cat.featured}
    @cats.sort_by{|cat| cat.reservations.count}.reverse[0..2]
    end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :find_cat, only: [:show, :edit, :update, :destroy]
  before_action :authorized, only: [:new]
  def homepage
  end

  def index
    if params[:q]
        @cats_atts = Cat.search_by_attributes(params[:q])
        @cats_owner = Cat.search_by_owner(params[:q])
        @cats_tags = Cat.search_by_tags(params[:q])
        @cats = (@cats_owner + @cats_atts + @cats_tags).uniq
      else
      @cats = Cat.all
    end
  end
  
  def new
    @cat = Cat.new
    @tags = Tag.all.sample(20)
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.owner_id = session[:user_id]
    if @cat.save
      redirect_to @cat
    else
      flash[:errors] = @cat.errors.full_messages
      redirect_to new_cat_path
    end
  end

  def search
    redirect_to "/cats/?q=#{params[:q]}"
  end

  def show
    @reviews = @cat.reviews
  end

  def edit
    @tags = Tag.all.sample(20)
    if session[:user_id] == @cat.owner_id
      render :edit
    else
      flash[:errors] = []
      redirect_to @cat
    end
  end
  
  def update
    if @cat.update(cat_params)
      redirect_to @cat
    else
      flash[:errors] = @cat.errors.full_messages
      redirect_to edit_cat_path(@cat)
    end
  end


  def destroy
    @cat.destroy
    redirect_to my_profile_path
  end

  def cat_stats
    @cats = Cat.all
    @featured_cat = Cat.featured
    @top3 = Cat.most_popular
  end




  private
  
  def find_cat
    @cat = Cat.find_by(id: params[:id])
  end

  def cat_params
    params.require(:cat).permit(:name, :owner_id, :neighborhood, :image, :breed, :price, tag_ids:[], tags_attributes: [:name])
  end

  def authorized_cat_owner?
    redirect_to my_profile_path unless session[:user_id] == Cat.find(params[:id]).owner_id
  end
    
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<%= form_with model: @cat do |f| %>
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p><br>
  <p><%= f.label :breed%></p>
  <p><%= f.text_field :breed %></p><br>
  <p><%= f.label :neighborhood %></p>
  <%= f.text_field :neighborhood %><br>
  <p><%= f.label :price %></p>
  $<%= f.number_field :price%><br>
  <p><%= f. label :image %></p>
  <%= f.file_field :image %><br>
  <p><%= f.label :tag_ids, "Tags" %></p><br>
  <%= f.collection_check_boxes :tag_ids, @tags, :id, :name%><br>
  <p><%= f.label :tags, "Add New Tags"%></p>
  <%= f.fields_for :tags, @cat.tags.build do |tags_fields| %>
    <%= tags_fields.text_field :name %></p>
  <%end%>
  <br>
  <%= f.submit %>
<%end%>

app/views/cats/cat_stats.html.erb
 

<h1>Cat Stats</h1>
<br><br>
<h2>Featured Cat</h2>
<%= render partial: "layouts/cat_display", locals: {cat: @featured_cat} %>
<br><br>
<h2>Top 3 Cats:</h2>
<% @top3.each do |cat| %>
  <%= render partial: "layouts/cat_display", locals: {cat: cat} %>
  <br><br>
<% end %>
</div>

app/views/cats/edit.html.erb
 

<h1>Edit <%=@cat.name%></h1>
<%= render 'form' %>
</div>

app/views/cats/homepage.html.erb
 
<div class='form' style="margin-left:100px; margin-right:100px;">
<p>Welcome to Cat App, the world's best -and only!- kitty rental service website created by Pat and Janae!</p>
<p>Please <%= link_to "sign up", new_user_path %> or <%=link_to "log in", login_path %> to start renting some cats!</p>
<br>
<p style="text-align:bottom;">Copyright <%="©️"%> 2019 Pat Bosman & Janae Hall</p>
</div>
</div>

app/views/cats/index.html.erb
 
  <h1>All Cats:</h1>
  <% if params[:q] %>
  <div class='button'>
    <%=button_to "Back To All Cats", cats_path, method: :get%>
  </div>
  <% end %>
  <br>
<%if @cats.empty? %>
<br><br>
  No Results Found For "<%= params[:q] %>"
  <br><br>
<% else %>
<br><br>
 <div class='cat'> 
 <%@cats.each do |cat| %>
    <%= render partial: "layouts/cat_display", locals: {cat: cat} %>
    <br>
    <div class='button'><%=button_to 'Rent This Cat', new_reservation_path(cat), method: :get%></div>
    <br><br><br>
  <%end%>
  
<% end  %></div>

app/views/cats/new.html.erb
 
<div class="form" style="margin-left:100px; margin-right:100px;">
  <h1>Add A New Cat</h1>
  <br><br>
  <%=render 'form'%>
</div>
</div>

app/views/cats/show.html.erb
 
  <br>
  <%= render partial: "layouts/cat_display", locals: {cat: @cat} %>
  <br>
  <% if session[:user_id] == @cat.owner_id %>
    <div class='button'><%= button_to "Edit #{@cat.name}", edit_cat_path(@cat), method: :get %></div>
    <br>
    <div class='button'><%= button_to "Retire #{@cat.name}", @cat, method: :delete %></div>
  <% else %>
    <div class='button'><%=button_to 'Rent This Cat', new_reservation_path(@cat), method: :get%></div>
  <% end %>
  <br><br><br>
  <div class='form'>
  <h3>Reviews of <%= @cat.name %></h3>
  <% if !@cat.reviews.empty? %>
    <div class='reviews'>
      <% @reviews.each do |review|%>
      <h5><%=link_to review.reservation.renter.name, review.reservation.renter %></h5>
      <%=("⭐️" * review.rating)+("☆" * (5 - review.rating)) %>
      <p>"<%= review.review %>"</p>
      <br>
      <% end %></div>
  <% else %>
    <p>None</p>
    <% end %>
</div>
</div>